### ISSUE TITLE
Final group capstone: set up the Kanban board

### ISSUE THREAD

**Issue by ZahraArshia** [ZahraArshia/book-flight-backend#11]
Hello 😄 
we are a group of four: @Thermiee, @saied2035, @ZahraArshia, and @nevisende 
the link to the backend kanban: https://github.com/ZahraArshia/book-flight-backend/projects/1
![image](https://user-images.githubusercontent.com/78906545/179183309-45dbb731-981f-40b2-95bf-43253e34300e.png)
the link to the frontend kanban: https://github.com/ZahraArshia/book-flight-frontend/projects/1
![image](https://user-images.githubusercontent.com/78906545/179183526-fb4a51f4-4f96-437d-a8a4-086642e46107.png)

**Comment by MuriloRoque** [comment]
Hi @ZahraArshia, @Thermiee, @saied2035, @nevisende,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
